---
services:
  freqtrade:
    # image: freqtradeorg/freqtrade:stable_freqai
    # # Enable GPU Image and GPU Resources
    # # Make sure to uncomment the whole deploy section
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

    # Build step - only needed when additional dependencies are needed
    build:
      context: .
      dockerfile_inline: |
        FROM freqtradeorg/freqtrade:stable_freqai

        ARG optuna_version
        ARG scikit_learn_extra_version
        ARG skimage_version
        USER root
        RUN apt-get update \
         && apt-get install -y --no-install-recommends build-essential \
         && rm -rf /var/lib/apt/lists/*
        USER ftuser
        RUN pip install --user --no-cache-dir \
            optuna==$${optuna_version} \
            optuna-integration==$${optuna_version} \
            optuna-dashboard \
            scikit-learn-extra==$${scikit_learn_extra_version} \
            scikit-image==$${skimage_version}
      args:
        - optuna_version=4.5.0
        - scikit_learn_extra_version=0.3.0
        - skimage_version=0.25.2
    restart: unless-stopped
    container_name: freqtrade-quickadapter
    environment:
      - TZ=Europe/Paris
    volumes:
      - "./user_data:/freqtrade/user_data"
    # Expose api on port 8081
    # Please read the https://www.freqtrade.io/en/stable/rest-api/ documentation
    # for more information.
    ports:
      - "0.0.0.0:8081:8080"
    # Default command used when running `docker compose up`
    command: trade
