"""Helpers package for reward_space_analysis tests."""

from .assertions import (
    assert_component_sum_integrity,
    assert_exit_factor_attenuation_modes,
    assert_exit_factor_invariant_suite,
    assert_exit_factor_plateau_behavior,
    assert_exit_mode_mathematical_validation,
    assert_hold_penalty_threshold_behavior,
    assert_pbrs_invariance_report_classification,
    assert_progressive_scaling_behavior,
    assert_relaxed_multi_reason_aggregation,
    assert_reward_calculation_scenarios,
    assert_single_active_component,
    assert_single_active_component_with_additives,
    build_validation_case,
    calculate_reward_with_defaults,
    execute_validation_batch,
    make_idle_penalty_test_contexts,
    run_relaxed_validation_adjustment_cases,
    run_strict_validation_failure_cases,
    simulate_samples_with_defaults,
)
from .configs import (
    DEFAULT_REWARD_CONFIG,
    DEFAULT_SIMULATION_CONFIG,
    ContextFactory,
    ExitFactorConfig,
    ProgressiveScalingConfig,
    RewardScenarioConfig,
    SimulationConfig,
    StatisticalTestConfig,
    ThresholdTestConfig,
    ValidationCallback,
    ValidationConfig,
    WarningCaptureConfig,
)
from .warnings import assert_diagnostic_warning, capture_warnings

__all__ = [
    "DEFAULT_REWARD_CONFIG",
    "DEFAULT_SIMULATION_CONFIG",
    "ContextFactory",
    "ExitFactorConfig",
    "ProgressiveScalingConfig",
    "RewardScenarioConfig",
    "SimulationConfig",
    "StatisticalTestConfig",
    "ThresholdTestConfig",
    "ValidationCallback",
    "ValidationConfig",
    "WarningCaptureConfig",
    "assert_component_sum_integrity",
    "assert_diagnostic_warning",
    "assert_exit_factor_attenuation_modes",
    "assert_exit_factor_invariant_suite",
    "assert_exit_factor_plateau_behavior",
    "assert_exit_mode_mathematical_validation",
    "assert_hold_penalty_threshold_behavior",
    "assert_pbrs_invariance_report_classification",
    "assert_progressive_scaling_behavior",
    "assert_relaxed_multi_reason_aggregation",
    "assert_reward_calculation_scenarios",
    "assert_single_active_component",
    "assert_single_active_component_with_additives",
    "build_validation_case",
    "calculate_reward_with_defaults",
    "capture_warnings",
    "execute_validation_batch",
    "make_idle_penalty_test_contexts",
    "run_relaxed_validation_adjustment_cases",
    "run_strict_validation_failure_cases",
    "simulate_samples_with_defaults",
]
